### ISSUE TITLE
no connection anymore since upgrade of Home Assistant

### ISSUE THREAD

**Issue by dondersj** [Wired-Square/homeassistant-sma-sw#13]
my connection with the Sma speedwire is gone since i upgraded my home assistant.

i now have:
Installation method
Home Assistant OS
Core
2025.6.0
Supervisor
2025.05.5
Operating System
15.2
Frontend
20250531.2

any idea what is going wrong??

![Image](https://github.com/user-attachments/assets/7cd7f2cb-4705-464b-9a7f-5c16bba4bdcf)

**Comment by abroeders** [comment]
Same here, logs:

Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 08:52:10 (4 occurrences)
Last logged: 12:43:52

Error setting up entry 192.168.100.245 for smasw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smasw/__init__.py", line 70, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by abroeders** [comment]
It was solved already. All you need to do is 'git pull' to pull the latest update from the git repo. After that, restart your home assistant and you're done.

**Comment by dondersj** [comment]
good to hear.
i just installed it and will check tomorrow when the sun is shining.

many thanks for your help.

**Comment by dondersj** [comment]
it is working again.
we can close this ticket.
i still have another issue see https://github.com/Wired-Square/homeassistant-sma-sw/issues/10
